name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
            submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to c0d3.sh
        uses: docker/login-action@v3
        with:
          registry: c0d3.sh
          username: ${{ vars.C0D3SH_USERNAME }}
          password: ${{ secrets.C0D3SH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./mqttwarn
          file: ./mqttwarn/Dockerfile.full
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: c0d3.sh/container/mqttwarn-docker:latest
#          tags: gbeine/mqttwarn:latest
